#include "Cube.h"
#include <iostream>

int main()
{
    //Cube c("WWWWWWWWWOOOGGGRRRBBBOOOGGGRRRBBBOOOGGGRRRBBBYYYYYYYYY");
    //Cube c("WWWWWWWWWBBBOOOGGGRRROOOGGGRRRBBBOOOGGGRRRBBBYYYYYYYYY");
    Cube c("WOHUTOETNHKHHNXKPOCXHHXPNTHXEPHXNXEUNHXENTXUHHUHXHUHEH");
    std::cout << c.isSolved() << std::endl;
}